DROP TABLE CREDENTIALS;

CREATE TABLE "CREDENTIALS" (
"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"LOGIN" VARCHAR(25) NOT NULL,
	"PASSWORD" VARCHAR(25) NOT NULL,
	CONSTRAINT primary_key_credentials PRIMARY KEY (ID)
);

INSERT INTO CREDENTIALS(LOGIN,PASSWORD) VALUES('admin','admin');